# Generated by Django 3.0.5 on 2020-04-21 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list_item', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listitemmodel',
            options={'verbose_name': 'День рождения'},
        ),
    ]
