# Generated by Django 3.0.5 on 2020-04-24 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        ('list_item', '0003_auto_20200424_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='listitemmodel',
            name='priority',
            field=models.SmallIntegerField(default=0, verbose_name='Приоритет'),
        ),
        migrations.AlterField(
            model_name='listitemmodel',
            name='expare_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listitemmodel',
            name='listmodel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ListModel', verbose_name='Список дел'),
        ),
        migrations.AlterField(
            model_name='listitemmodel',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Название'),
        ),
    ]
