# Generated by Django 3.0.5 on 2020-04-25 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list_item', '0004_auto_20200424_1809'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listitemmodel',
            options={'verbose_name': 'Элемент списка'},
        ),
        migrations.RenameField(
            model_name='listitemmodel',
            old_name='listmodel',
            new_name='list',
        ),
    ]
