# Generated by Django 3.0.5 on 2020-04-25 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list_item', '0005_auto_20200425_1837'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listitemmodel',
            old_name='list',
            new_name='listmodel',
        ),
    ]
